python3 PCA.py mnist layer_1
python3 PCA.py mnist layer_2
python3 PCA.py mnist layer_3
python3 PCA.py mnist layer_4
python3 PCA.py mnist layer_all
python3 PCA.py func layer_1
python3 PCA.py func layer_2
python3 PCA.py func layer_3
python3 PCA.py func layer_4
python3 PCA.py func layer_all
